# Generated by Django 3.0.5 on 2020-04-15 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('no_HP', models.CharField(max_length=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userphone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nama', models.CharField(max_length=50)),
                ('nik', models.CharField(max_length=16)),
                ('alamat', models.TextField()),
                ('tanggal_lahir', models.CharField(max_length=8)),
                ('no_HP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='c19_server.UserPhone')),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gejala_demam', models.BooleanField(default=False)),
                ('usia', models.BooleanField(default=False)),
                ('kontak', models.BooleanField(default=False)),
                ('aktivitas', models.BooleanField(default=False)),
                ('gejala_lain', models.TextField()),
                ('kategori', models.PositiveSmallIntegerField(default=0)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='c19_server.UserID')),
            ],
        ),
    ]
